// Vertical configuration for all demo sites
// Update values here → all demo pages pull from this

export const VERTICALS = {
  plumbing: {
    name: "Bay Area Plumbing Co.",
    tagline: "Reliable Service. Honest Pricing.",
    accent: "#0891B2",
    industry: "Plumbing",
    location: "San Francisco, CA",
    phone: "(415) 555-0142",
    email: "info@bayareaplumbing.com",
    address: "1234 Mission St, San Francisco, CA 94103",
    hours: "Mon–Sat: 7AM–7PM",
    services: ["Emergency Repairs", "Water Heater Installation", "Drain Cleaning", "Pipe Replacement", "Fixture Installation"],
    about: "Family-owned plumbing company serving the Bay Area for over 20 years. Licensed, bonded, and insured.",
    cta: "Schedule Service Today",
    cta_sub: "Same-day appointments available",
    description: "Service-focused plumbing website with instant booking, service area mapping, and trust signals that convert browsers into booked appointments.",
    demoUrl: "/demo/plumbing",
  },
  hvac: {
    name: "CoolPro HVAC",
    tagline: "Stay Cool. Stay Comfortable.",
    accent: "#0D9488",
    industry: "HVAC",
    location: "Phoenix, AZ",
    phone: "(602) 555-0198",
    email: "service@coolprohvac.com",
    address: "7842 W Camelback Rd, Phoenix, AZ 85033",
    hours: "Mon–Fri: 7AM–6PM | Sat: 8AM–2PM",
    services: ["AC Repair & Installation", "Heating Service", "Indoor Air Quality", "Preventative Maintenance", "Duct Cleaning"],
    about: "Top-rated HVAC contractor in Phoenix with 15+ years of experience. NATE-certified technicians.",
    cta: "Get a Free Estimate",
    cta_sub: "Licensed & bonded",
    description: "Seasonal HVAC website with urgency-driven CTAs, maintenance plans showcase, and fast quote request forms that capture high-intent leads.",
    demoUrl: "/demo/hvac",
  },
  electrician: {
    name: "Current Electric LLC",
    tagline: "Power Done Right.",
    accent: "#CA8A04",
    industry: "Electrical",
    location: "Austin, TX",
    phone: "(512) 555-0231",
    email: "jobs@currentelectricatx.com",
    address: "5501 Congress Ave, Austin, TX 78745",
    hours: "Mon–Sat: 7AM–6PM",
    services: ["Panel Upgrades", "Lighting Installation", "EV Charger Setup", "Whole-Home Wiring", "Safety Inspections"],
    about: "Licensed electricians serving Austin and surrounding counties. Free estimates. No overtime charges.",
    cta: "Request Service",
    cta_sub: "Available for emergencies",
    description: "Professional electrical services website with safety certifications front-and-center, service-specific landing pages, and instant scheduling.",
    demoUrl: "/demo/electrician",
  },
  roofer: {
    name: "TopTier Roofing",
    tagline: "We Roof It Right.",
    accent: "#EA580C",
    industry: "Roofing",
    location: "Dallas, TX",
    phone: "(214) 555-0318",
    email: "inspections@toptierroofing.com",
    address: "3200 Main St, Dallas, TX 75226",
    hours: "Mon–Sat: 8AM–5PM",
    services: ["Shingle Replacement", "Metal Roofing", "Storm Damage Repair", "Gutter Installation", "Free Inspections"],
    about: "GAF-certified roofing contractor. 10-year warranty on labor. Hundreds of 5-star reviews.",
    cta: "Book Inspection",
    cta_sub: "No-obligation roof assessment",
    description: "Roofing contractor website with project galleries, insurance claim guidance, and inspection request forms optimized for storm damage season.",
    demoUrl: "/demo/roofer",
  },
  "auto-repair": {
    name: "Westside Auto Care",
    tagline: "Honest Auto Repair You Can Trust.",
    accent: "#DC2626",
    industry: "Auto Repair",
    location: "Los Angeles, CA",
    phone: "(323) 555-0429",
    email: "book@westsideautocare.com",
    address: "8821 Santa Monica Blvd, Los Angeles, CA 90069",
    hours: "Mon–Fri: 7AM–6PM | Sat: 8AM–3PM",
    services: ["Brake Repair", "Oil Changes", "Engine Diagnostics", "Tire Replacement", "Smog Check"],
    about: "ASE-certified mechanics. Family-owned since 1998. No surprise pricing — ever.",
    cta: "Schedule Repair",
    cta_sub: "Walk-ins welcome",
    description: "Trust-building auto repair website with transparent pricing, service reminder features, and appointment scheduling that reduces no-shows.",
    demoUrl: "/demo/auto-repair",
  },
  salon: {
    name: "Glow Studio Salon",
    tagline: "Where Style Meets Community.",
    accent: "#DB2777",
    industry: "Salon & Spa",
    location: "Atlanta, GA",
    phone: "(404) 555-0567",
    email: "hello@glowstudiosalon.com",
    address: "1100 Peachtree St NE, Atlanta, GA 30309",
    hours: "Tue–Sat: 9AM–7PM",
    services: ["Hair Styling", "Color & Highlights", "Keratin Treatments", "Extensions", "Bridal Styling"],
    about: "Award-winning salon in the heart of Midtown. Book online or walk in. Natural hair specialist.",
    cta: "Book Appointment",
    cta_sub: "Online booking available",
    description: "Elegant salon website with visual stylist portfolios, service menu with pricing, and seamless online booking integration.",
    demoUrl: "/demo/salon",
  },
  restaurant: {
    name: "Mama Rosa's Italian Kitchen",
    tagline: "Authentic Italian. Made Fresh Daily.",
    accent: "#EA580C",
    industry: "Restaurant",
    location: "Houston, TX",
    phone: "(713) 555-0789",
    email: "reservations@mamarosas.com",
    address: "4201 Main St, Houston, TX 77002",
    hours: "Tue–Sun: 11AM–10PM",
    services: ["Dine-In", "Takeout & Delivery", "Private Events", "Catering", "Gift Cards"],
    about: "Houston's favorite family-owned Italian restaurant since 1985. House-made pasta daily.",
    cta: "View Menu & Order",
    cta_sub: "Order ahead, skip the wait",
    description: "Restaurant website with embedded menu, reservation system, and catering inquiry forms that capture group booking revenue.",
    demoUrl: "/demo/restaurant",
  },
  "real-estate": {
    name: "Horizon Realty Group",
    tagline: "Your Home. Our Mission.",
    accent: "#2563EB",
    industry: "Real Estate",
    location: "Denver, CO",
    phone: "(303) 555-0847",
    email: "listings@horizonrealtyco.com",
    address: "1600 Champa St, Denver, CO 80202",
    hours: "Mon–Sun: 9AM–7PM",
    services: ["Home Buyers", "Home Sellers", "Investment Properties", "Relocation Services", "Property Management"],
    about: "Denver's most trusted boutique real estate team. Average 18 years experience per agent.",
    cta: "Browse Listings",
    cta_sub: "Free market analysis",
    description: "Boutique real estate website with agent profiles, listing showcases, and lead capture forms for buyer/seller inquiries.",
    demoUrl: "/demo/real-estate",
  },
  "law-firm": {
    name: "Morrison & Associates Law",
    tagline: "Fighting for You. Every Step.",
    accent: "#1E3A5F",
    industry: "Law Firm",
    location: "Chicago, IL",
    phone: "(312) 555-0923",
    email: "intake@morrisonlawchicago.com",
    address: "225 W Wacker Dr, Chicago, IL 60606",
    hours: "Mon–Fri: 8AM–6PM",
    services: ["Personal Injury", "Family Law", "Criminal Defense", "Estate Planning", "Business Litigation"],
    about: "Award-winning Chicago law firm. Contingency-fee personal injury cases. Free consultations.",
    cta: "Get Free Consultation",
    cta_sub: "Se habla español",
    description: "Professional law firm website with practice area pages, attorney credentials, and confidential consultation request forms.",
    demoUrl: "/demo/law-firm",
  },
  insurance: {
    name: "Shield Insurance Partners",
    tagline: "Protection You Can Count On.",
    accent: "#065F46",
    industry: "Insurance",
    location: "Miami, FL",
    phone: "(305) 555-0176",
    email: "quotes@shieldinsurancepartners.com",
    address: "1000 Brickell Ave, Miami, FL 33131",
    hours: "Mon–Fri: 9AM–5PM",
    services: ["Auto Insurance", "Homeowners Insurance", "Business Insurance", "Life Insurance", "Health Plans"],
    about: "Independent agency representing 30+ carriers. We'll shop the best rates for you.",
    cta: "Get a Quote",
    cta_sub: "No spam, no pressure",
    description: "Insurance agency website with carrier comparisons, quote request forms, and trust-building testimonials from satisfied clients.",
    demoUrl: "/demo/insurance",
  },
  clothing: {
    name: "NOIR Apparel",
    tagline: "Streetwear. Elevated.",
    accent: "#7C3AED",
    industry: "Clothing Brand",
    location: "New York, NY",
    phone: "(212) 555-0341",
    email: "orders@noirapparel.co",
    address: "45 Great Jones St, New York, NY 10012",
    hours: "Online 24/7 | Brooklyn Showroom: Sat–Sun 12PM–6PM",
    services: ["Men's Streetwear", "Limited Drops", "Custom Designs", "Wholesale", "Size Exchanges"],
    about: "NYC-born streetwear brand. 100% designed in Brooklyn. Limited runs, no restocks.",
    cta: "Shop the Collection",
    cta_sub: "Free shipping over $75",
    description: "Fashion-forward brand website with lookbook aesthetics, product storytelling, and email capture for drop notifications.",
    demoUrl: "/demo/clothing",
  },
  ecommerce: {
    name: "Vitality Nutrition",
    tagline: "Fuel Your Best Self.",
    accent: "#059669",
    industry: "E-Commerce",
    location: "Portland, OR",
    phone: "(971) 555-0674",
    email: "support@vitalitynutrition.co",
    address: "2100 SE Burnside Rd, Portland, OR 97214",
    hours: "Customer Support: Mon–Fri 8AM–8PM",
    services: ["Protein Powders", "Pre-Workout", "Vitamins & Minerals", "Meal Replacements", "Gift Cards"],
    about: "Science-backed supplements made with clean ingredients. 60-day money-back guarantee.",
    cta: "Shop Now",
    cta_sub: "Free shipping on orders over $50",
    description: "Clean supplement e-commerce website with ingredient transparency, customer reviews, and subscription options for recurring revenue.",
    demoUrl: "/demo/ecommerce",
  },
  "tech-company": {
    name: "Nexus AI",
    tagline: "Intelligent Automation for Modern Enterprises",
    accent: "#22d3ee",
    industry: "Tech Company",
    location: "Austin, TX",
    phone: "(512) 555-0192",
    email: "contact@nexus-ai.com",
    address: "8901 Data Blvd, Austin, TX 78701",
    hours: "Mon–Fri: 8AM–6PM",
    services: ["Agentic Workflows", "Data Intelligence", "Scalable Automation", "Custom Software", "Cloud Infrastructure"],
    about: "Enterprise AI platform helping businesses deploy intelligent automation at scale. Trusted by 200+ enterprises worldwide.",
    cta: "Request Demo",
    cta_sub: "Trusted by 200+ enterprises",
    description: "Enterprise AI platform demo with agentic workflows, data intelligence, and scalable automation showcase.",
    demoUrl: "/demo/tech-company",
    mockupImage: "/wilteckinc-preview.jpg",
  },
} as const;

export interface Vertical {
  name: string;
  tagline: string;
  accent: string;
  industry: string;
  location: string;
  phone: string;
  email: string;
  address: string;
  hours: string;
  services: string[];
  about: string;
  cta: string;
  cta_sub: string;
  description: string;
  demoUrl: string;
  mockupImage?: string;
}

export type VerticalId = keyof typeof VERTICALS;